ProyectoMovie/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('movie.urls')),
    path('blog/', include('blog.urls')),
   
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path("", views.renderPosts, name="posts"),
    path("post/<int:post_id>", views.post_detail, name="post_detail"),
    

]

movie/urls.py
from django.urls import path
from movie import views
from django.conf import settings
from django.conf.urls.static import static
from .models import Genero


urlpatterns = [
    
    path('', views.home, name="Home"),
    
    path('pelicula/<int:pelicula_id>/', views.pelicula_detail, name='pelicula_detail'),
    path('genero/', views.generos, name='genero'),
    path('estreno/', views.estreno, name='estreno'),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

blog/models.py
from django.db import models
import datetime
from ckeditor.fields import RichTextField


class Post(models.Model):

    """
    Creamos nuestro post
    RichTextField está muy interesante para poder editar y manipular la descripción a nuestra medida 
    al igual que si queremos añadir imagenes en la descripción, url, emoticonos, vídeos y más cosas.

    """
    title = models.CharField(max_length=100)
    description = RichTextField()
    image = models.ImageField(upload_to="blog/images")
    date = models.DateField(default=datetime.date.today)



    class Meta:
        verbose_name = 'Post'
        verbose_name_plural = 'Posts'
        ordering = ['-id']

   
   
    def __str__(self) -> str:
        return self.title
    
 

movie/models.py
from django.db import models

from django.db import models
from django.db.models.fields import CharField, DateField, URLField
from django.db.models.fields.files import ImageField
from datetime import date
from ckeditor.fields import RichTextField





class Genero(models.Model):
    nombre = models.CharField(max_length=100)


    class Meta:
        verbose_name = 'Genero'
        verbose_name_plural = 'Generos'

    def __str__(self):
        return self.nombre
    

class Pelicula(models.Model):
    titulo = CharField(max_length=100)
    descripcion = RichTextField()
    imagen = ImageField(upload_to="movie/images")
    genero = models.ManyToManyField(Genero)
    duracion = CharField(max_length=10)
    rate = CharField(max_length=6)
    url = URLField(blank=True)
    trailer = URLField(blank=True)
    fecha = DateField(default=date.today)
    director = CharField(max_length=50)
    reparto = models.TextField()


    class Meta:
        verbose_name = 'Pelicula'
        verbose_name_plural = 'Peliculas'
        ordering = ['titulo']

    def __str__(self) -> str:
        return self.titulo


class Estreno(models.Model):
    titulo = CharField(max_length=100)
    fecha_estreno = DateField(default=date.today)
    imagen = ImageField(upload_to="estreno/images")


    def __str__(self) -> str:
        return self.titulo

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post
from django.db.models import Q


def renderPosts(request):

    """
    Traemos los posts que están ordenados de más recientes a antiguos.
    Hacemos una filtración de los posts mediante búsqueda de título o fecha en la barra de búsqueda que 
    hemos creado en base.html 
    
    """    
    posts = Post.objects.order_by("-date")

    if "buscar" in request.GET:
        queryset = request.GET.get("buscar")
        if queryset:                        
            posts = Post.objects.filter(
                Q(title__icontains = queryset) | 
                Q(date__icontains = queryset)                 
                
            ).distinct()

    return render(request, "blog.html", {"posts": posts})


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    return render(request, "post_detail.html", {"post": post})

movie/views.py
from django.shortcuts import render,get_object_or_404
from .models import Pelicula, Estreno, Genero
from django.db.models import Q

def home(request):
    """
    Esta parte es igual que en el blog, traemos todas las películas y hacemos un filtrado de búsqueda
    en el que podemos buscar por: título, género, fecha, rate, duración y director, en la barra de búsqueda
    todo esto lo devolvemos en el archivo home.html

    """
    peliculas = Pelicula.objects.all()
    if "buscar" in request.GET:        
        queryset = request.GET.get("buscar")     
        if queryset:                        
            peliculas = Pelicula.objects.filter(
                Q(titulo__icontains = queryset) |               
                Q(genero__nombre__icontains = queryset) |
                Q(fecha__icontains = queryset) |
                Q(rate__icontains = queryset) |
                Q(duracion__icontains = queryset) |
                Q(director__icontains = queryset)
                 
                
            ).distinct()
    
    return render(request, "home.html", {"peliculas": peliculas})


def peliculas(request):
    
    total_peliculas = Pelicula.objects.count()
    peliculas = Pelicula.objects.order_by("-date")
    return render(request, "/", {"peliculas": peliculas, "total_peliculas": total_peliculas})


        
def pelicula_detail(request, pelicula_id):
    pelicula = Pelicula.objects.get(pk=pelicula_id)
    return render(request, 'pelicula_detail.html', {'pelicula': pelicula})

def generos(request):
    generos = Genero.objects.all()
    
    # Resto del código de la vista
    return render(request, 'pelicula_genero.html', {'generos': generos})

def estreno(request):
    estreno = Estreno.objects.all()
    return render(request, 'estreno.html', {'estreno': estreno})


""" def genero(request, genero_id):
    genero = get_object_or_404(Genero, id=genero_id)
    peliculas = Pelicula.objects.filter(generos__id=genero_id)
    context = {'genero': genero, 'peliculas': peliculas}
    return render(request, 'pelicula_genero.html', context)
 """

blog/templates/blog.html
{% extends 'base.html' %}

{% block content %}

<h2 class=" text-left text-white d-none d-lg-block"style="font-size: 25px; text-align: center;color: #2a2e2e; margin-top:3%;" > Artículos </h2>
<div class="footer-divider" style="width:41.6%; margin: 0 auto"></div>
{% for post in posts %}
<div class="py-3" style="margin-top:2%">
  <div class="card card-body" style="width:42%; margin: 0 auto; align-items: center; ">
      <div class="col-9" >
        <h2 style="color: #2a2e2e;">{{post.title}}</h1>
        <div class="footer-divider" ></div>
        <p>{{post.description|striptags|truncatechars:100}}</p>
        <a href="{% url 'blog:post_detail' post.id %}" style="text-decoration: none; color:rgb(148, 147, 147)">Leer artículo...</a>
        <p>{{post.date|date:'M d Y'|upper}}</p>
      </div>
      <div class="row">      
        <img class="img-fluid" src="{{post.image.url}}" alt="{{post.title}}" style=" margin: 0 auto;">
      </div>
    </div>
  </div>
{% endfor %}
{% endblock %}
</div>

blog/templates/post_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container" style="margin-top: 5%;">
  <div class="row">
      <h2 style="text-align: center; color: #2a2e2e; margin-top: 5%; ">{{post.title}}</h2>
      <div class="footer-divider" style="width: 98%; margin: 0 auto;"></div> 
      <div class="col-md-4" style="margin-top: 3%;">
      <h2 class="my-2 h5 text-muted">{{post.date|date:'F d Y'}}</h2>
      <img src="{{post.image.url}}" alt="{{post.title}}" class="img-fluid">
    </div>
    <div class="col-md-8" style="margin-top: 5%; margin-bottom: 4%;">
    <p >{{post.description|safe}}</p>
  </div>
</div>
{% endblock %}

movie/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}

    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Movies</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Josefin+Sans:wght@200;300;400;500&family=Raleway:wght@100;200;300;400;500&family=Roboto:wght@300;400;700&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous" />
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/particlesjs/2.2.3/particles.min.js"></script>
    <link rel="stylesheet" href="{% static 'main.css' %}">
    <link rel="stylesheet" href="{% static 'gestion.css' %}">       
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<body style="background-color: #cfcfcf;">
 <!-- Navbar -->
 <nav class="navbar navbar-expand-lg navbar-dark py-lg-4" id="mainNav" style="background-color: #244d61" >
    <div class="container">        
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav mx-auto">      
          <li class="nav-item {% if request.path == '/' %}active{% endif %} px-lg-4">
            <a class="nav-link text-uppercase text-expanded" href="{% url 'Home' %}" >Inicio</a>
          </li> 
          <!-- <li class="nav-item {% if request.path == '/blog/' %}active{% endif %} px-lg-4">
            <a class="nav-link text-uppercase text-expanded" href="{% url 'blog:posts' %}">Películas</a>
          </li>   
          <li class="nav-item {% if request.path == '/genero/' %}active{% endif %} px-lg-4">
            <a class="nav-link text-uppercase text-expanded" href="{% url 'genero' %}">generos</a>
          </li> 
          <li class="nav-item {% if request.path == '/estreno/' %}active{% endif %} px-lg-4">
            <a class="nav-link text-uppercase text-expanded" href="{% url 'estreno' %}">Estrenos</a>
          </li>  -->      
          <li class="nav-item {% if request.path == '/blog/' %}active{% endif %} px-lg-4">
            <a class="nav-link text-uppercase text-expanded" href="{% url 'blog:posts' %}" >Blog</a>
          </li>
          <li>
          <form >
            <div class="input-group" >
              <input type="text" class="form-control" placeholder="Buscar" name="buscar" 
                style="border-radius: 20px; color: rgb(255, 165, 0); background-color: #605e5e;margin-right:35% ">
              <button type="submit" class="btn" style="border-radius: 20px;
                color: rgb(0, 0, 0); background-color: rgb(255, 165, 0);margin-right:-40% ">
                Buscar
              </button>
            </div>
          </form>
        </li>
        </ul>
      </div>        
</nav>
 
   {% block content %}
   {% endblock %}  
    <script src="{% static 'movie/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'movie/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'movie/vendor/bootstrap/js/bootstrap.bundle.js' %}"></script>
    <script src="{% static 'movie/vendor/jquery/jquery.tagcanvas.js' %}"></script>  
    <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
    <a class="ir-arriba  fa fa-chevron-circle-up" style="font-size:36px; margin-bottom: 3%; color:rgb(105, 4, 4); margin-right: 1%;" ></a>

    <div style="float: right;"> 
    <script>
          $(document).ready(function(){

          $('.ir-arriba').click(function(){
            $('body, html').animate({
              scrollTop: '0px'
            }, 300);
          });

          $(window).scroll(function(){
            if( $(this).scrollTop() > 0 ){
              $('.ir-arriba').slideDown(300);
            } else {
              $('.ir-arriba').slideUp(300);
            }
          });

          });

          $('.hamburger').on('click', function() {
          $(this).toggleClass('opened');
          });

    </script>
  </div>
</body>
</html>

movie/templates/estreno.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<div class="container" style="margin-top: 5%;">
  <div class="col-md-8">
  <h1>Películas próximamente en cartelera</h1>  
  </div>
  {% if estreno %}
    <ul>
      {% for estrenos in estreno %}
      <p> <strong>{{ estrenos.fecha_estreno|date:"d/m/y" }}</strong></p>
        <li>{{ estrenos.titulo }} - </li>
      {% endfor %}
    </ul>
  {% else %}
    <p>No hay películas próximamente en cartelera</p>

  {% endif %}
  </div>
</div>
{% endblock %}

movie/templates/home.html
{% extends "base.html" %}

{% load static %}

{% block content %}


 
<h2 class=" text-left text-white d-none d-lg-block"style="font-size: 22px; text-align: center;color: #2a2e2e; margin-top:3%" > Galería de Películas </h2>
<div class="footer-divider" style="width:50%; margin: 0 auto"></div>
<div class="row " style="width: 100%; padding: 5% 10%; margin: 3% 3% 3% 3%">
{% for pelicula in peliculas %}
<div class="col-md-3" style="margin: 0 auto;">
  <div class="card " style="width: 69%; height:100%; border-radius: 20px; ">
      <img src="{{pelicula.imagen.url }}" class="img-fluid " style="border-radius: 20px; width: 300px; height: 350px; margin: 0 auto;">
      <div class="card-body col-md-12 float-md-left blog-thumbnail" style="text-align: center;">    
      <a href="" class="card-title"style="text-align: center; color:black; text-decoration: none; ">{{ pelicula.titulo|truncatechars:100 }}</a>
  </div>
  <div class="card-text" style=" align-items: center;">                  
    <a href="{{pelicula.url}}" class="btn " target="__blank"
    style="text-align: center; border-radius: 20px;   color: #787575;
    background-color: rgb(255, 165, 0); margin-bottom: 5%; " 
    >
    <i class="fa fa-play-circle-o" style="font-size: 20px;"></i>
    Ver Película
  </a>   
  <a href="{% url 'pelicula_detail' pelicula.id %}" style="color: rgb(148, 147, 147); margin-right: 1.1rem; ">Leer más...</a>     
</div> 
  </div>
  </div>
{% endfor %}
{% endblock %}
</div>

movie/templates/pelicula_detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<div class="container" style="margin-top: 5%;">
    <div class="row">
      <div class="col-md-4">
        <img src="{{ pelicula.imagen.url }}" alt="{{ pelicula.titulo }}" class="img-fluid">
      </div>
      <div class="col-md-8">
        <h2 style="color: black; font: bold;">{{ pelicula.titulo }}</h2>
        <p><strong>Director:</strong> {{ pelicula.director }}</p>
        <p><strong>Reparto:</strong> {{ pelicula.reparto }}</p>
        <p><strong>Año:</strong> {{ pelicula.fecha }}</p>
        <p><strong>Duración:</strong> {{ pelicula.duracion }}</p>
        <p><strong>IMDb:</strong><i class="fa fa-star" style="color:rgb(255,165,0)"></i> {{ pelicula.rate }}</p>
        <p><strong>Géneros:</strong>           
            {% for genero in pelicula.genero.all %}
              {{ genero.nombre }}
              {% if not forloop.last %}, {% endif %}
            {% endfor %}          
        </p>
        <p><strong>Sinopsis:</strong>{{ pelicula.descripcion }}</p>
        <div class="card-text" style=" align-items: center;">                  
            <a href="{{pelicula.url}}" class="btn " target="__blank"
            style="text-align: center; border-radius: 20px;   color: #d4d1d1;
            background-color: rgb(12, 101, 152); margin-bottom: 5%; " 
            >
            <i class="fa fa-play-circle-o" style="font-size: 20px;"></i>
            Ver Película
          </a> &nbsp; 
          <a href="{{pelicula.trailer}}" class="btn " target="__blank"
          style="text-align: center; border-radius: 20px;   color: #2f2e2e;
          background-color: transparent; margin-bottom: 5%; " 
          >
          <i class="fa fa-play-circle-o" style="font-size: 20px;"></i>
          Trailer
        </a>    
        </div> 
        <div class="card-text" style=" align-items: center;">                 
        </div> 
      </div>
    </div>
  </div>
{% endblock %}

movie/templates/pelicula_genero.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<div class="container">
    <h1>Géneros de películas</h1>
    {% for genero in generos %}
      <section>
        <h2>{{ genero.nombre }}</h2>
        <ul>
          {% for pelicula in genero.pelicula_set.all %}
            <li>{{ pelicula.titulo }}</li>
          {% empty %}
            <li>No hay películas en este género</li>
          {% endfor %}
        </ul>
      </section>
    {% endfor %}
  </div>
{% endblock %}

movie/templates/pelicula_por_genero.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <div class="container">
    <h1>Géneros de películas</h1>
    {% for genero in generos %}
      <section>
        <h2>{{ genero.nombre }}</h2>
        <ul>
          {% for pelicula in genero.pelicula_set.all %}
            <li>{{ pelicula.titulo }}</li>
          {% empty %}
            <li>No hay películas en este género</li>
          {% endfor %}
        </ul>
        <a href="{% url 'peliculas:pelicula_por_genero' genero.id %}">Ver todas las películas de este género</a>
      </section>
    {% endfor %}
  </div>
{% endblock %}